(()=>{'use strict';const $=id=>document.getElementById(id);const fmt=x=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:3}).format(x);
$('pulse').innerHTML=`<section class="card controls"><div><label for="pf">Rechteckfrequenz <output id="pf-out"></output></label><input id="pf" type="range" min="10" max="200" step="10" value="100"><label for="pw">Pulsbreite <output id="pw-out"></output></label><input id="pw" type="range" min="0.1" max="9.9" step="0.1" value="1"></div><div><label for="pa">Abtastfrequenz <output id="pa-out"></output></label><input id="pa" type="range" min="20" max="5000" step="20" value="200"><label for="po">Startversatz der Abtastung <output id="po-out"></output></label><input id="po" type="range" min="0" max="95" step="5" value="50"></div><div class="buttons"><button id="miss">Impulse verpassen</button><button id="catch">Impulse erfassen</button><button id="preset-reset">Zurücksetzen</button></div></section><section class="card"><span class="eyebrow">RECHTECK UND MESSWERTE</span><h2>Erfasst das Messgerät jeden Impuls?</h2><div class="legend"><span class="blue">● Originalsignal: 0 V / 3 V</span><span style="color:#00846b">● Messpunkte</span><span style="color:#bb4242">▧ Verpasster Impuls</span></div><div class="plot" id="pulse-chart"></div><label class="check"><input type="checkbox" id="hold" checked> Gehaltenen Messwert einblenden (orange)</label><p class="muted">Die orange Stufe beginnt am jeweiligen Messzeitpunkt. Sie ist eine Halte-Darstellung, keine eindeutige Rekonstruktion.</p><div class="stats"><div><small>Periodendauer / Pulsbreite</small><strong id="pulse-times"></strong></div><div><small>Abtastperiode</small><strong id="pulse-ta"></strong></div><div><small>Erfasste / verpasste Impulse</small><strong id="pulse-count"></strong></div></div><p id="pulse-status" role="status"></p></section><details class="card"><summary>Was zeigt dieses Modell?</summary><p>Ein Impuls wird als erfasst gezählt, wenn mindestens ein Messpunkt in seiner High-Phase liegt. Gezeigt werden vier vollständige Perioden. Verändern Sie auch den Startversatz: Dieselbe Abtastfrequenz kann je nach Lage der Messzeitpunkte andere Ergebnisse liefern.</p><p>Für eine vom Startversatz unabhängige Erfassung eines idealen Impulses wählen wir hier Tₐ kleiner als die Pulsbreite. Das garantiert noch keine genaue Bestimmung seiner Flanken oder Form. Eine ideale Rechteckschwingung enthält beliebig hohe Frequenzanteile; allein die doppelte Rechteckfrequenz reicht nicht zur exakten Rekonstruktion.</p><p>Idealisiertes Modell ohne Rauschen, Quantisierung und endliche Belichtungs- oder Erfassungsdauer. Der Beginn eines Impulses gehört zur High-Phase, sein Ende zur Low-Phase.</p></details>`;
function render(){const f=+$('pf').value,T=1000/f;$('pw').max=(T-.1).toFixed(1);if(+$('pw').value>=T)$('pw').value=(T-.1).toFixed(1);const width=+$('pw').value,fa=+$('pa').value,ta=1000/fa,offset=+$('po').value/100*ta,end=4*T;
const high=t=>{let phase=t%T;if(Math.abs(phase-T)<1e-8||Math.abs(phase)<1e-8)phase=0;return phase<width-1e-8?3:0;};const samples=[];for(let k=0;offset+k*ta<end-1e-8;k++){const t=offset+k*ta;samples.push([t,high(t)]);}let missed=[];for(let j=0;j<4;j++)if(!samples.some(([t,v])=>v===3&&t>=j*T-1e-8&&t<(j+1)*T-1e-8))missed.push(j);
$('pf-out').textContent=fmt(f)+' Hz';$('pw-out').textContent=fmt(width)+' ms ('+fmt(width/T*100)+' %)';$('pa-out').textContent=fmt(fa)+' Hz';$('po-out').textContent=fmt(offset)+' ms';$('pulse-times').textContent=fmt(T)+' ms / '+fmt(width)+' ms';$('pulse-ta').textContent=fmt(ta)+' ms';$('pulse-count').textContent=(4-missed.length)+' / '+missed.length;$('pulse-status').textContent=missed.length?missed.length+' von 4 Impulsen liegen vollständig zwischen den Messzeitpunkten.':'Alle vier Impulse werden mindestens einmal erfasst.';
const x=t=>65+t/end*865,y=v=>240-v*60;let s='<svg viewBox="0 0 960 300" role="img" aria-label="Rechtecksignal mit Abtastpunkten und markierten verpassten Impulsen"><defs><pattern id="missed-hatch" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8L8 0" stroke="#dfaaaa" stroke-width="1"/></pattern></defs>';
for(let j=0;j<=8;j++){const t=j*end/8;s+=`<path d="M${x(t)} 30V240" stroke="#e0e6ee"/><text x="${x(t)}" y="265" text-anchor="middle" font-size="15">${fmt(t)}</text>`;}for(let v=0;v<=3;v++)s+=`<path d="M65 ${y(v)}H930" stroke="#e0e6ee"/><text x="48" y="${y(v)+5}" text-anchor="end" font-size="15">${v}</text>`;for(const j of missed)s+=`<rect x="${x(j*T)}" y="30" width="${x(width)-65}" height="210" fill="url(#missed-hatch)"/>`;
let d=`M65 ${y(0)}`;for(let j=0;j<4;j++)d+=`L${x(j*T)} ${y(0)}V${y(3)}H${x(j*T+width)}V${y(0)}H${x((j+1)*T)}`;s+=`<path d="${d}" fill="none" stroke="#005a9e" stroke-width="2.3"/>`;
if($('hold').checked&&samples.length){let d=`M${x(samples[0][0])} ${y(samples[0][1])}`;for(let i=1;i<samples.length;i++)d+=`H${x(samples[i][0])}V${y(samples[i][1])}`;d+=`H${x(end)}`;s+=`<path d="${d}" fill="none" stroke="#cf7400" stroke-width="2" stroke-dasharray="6 3"/>`;}
for(const [t,v] of samples)s+=`<circle class="pulse-sample" cx="${x(t)}" cy="${y(v)}" r="3" fill="#00846b"><title>${fmt(t)} ms: ${v} V</title></circle>`;s+='<text x="65" y="20" font-size="15">U / V</text><text x="930" y="293" text-anchor="end" font-size="15">t / ms</text></svg>';$('pulse-chart').innerHTML=s;}
['pf','pw','pa','po','hold'].forEach(id=>$(id).addEventListener('input',render));function preset(fa){$('pf').value=100;$('pw').value=1;$('pa').value=fa;$('po').value=50;$('hold').checked=true;render();}$('miss').onclick=()=>preset(200);$('catch').onclick=()=>preset(2000);$('preset-reset').onclick=()=>preset(200);
for(const name of ['fourier','pulse'])$('tab-'+name).onclick=()=>{for(const n of ['fourier','pulse']){$(n).hidden=n!==name;$('tab-'+n).setAttribute('aria-pressed',String(n===name));}if(name==='pulse')render();};render();})();
